//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace server.Infrastructure {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesPrompts {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesPrompts() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("server.Infrastructure.Services.ResourcesPrompts", typeof(ResourcesPrompts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AUDIO_TRANSCRIPTION_PROMPT {
            get {
                return ResourceManager.GetString("AUDIO_TRANSCRIPTION_PROMPT", resourceCulture);
            }
        }
        
        public static string ANSWER_GENERATION_PROMPT {
            get {
                return ResourceManager.GetString("ANSWER_GENERATION_PROMPT", resourceCulture);
            }
        }
        
        public static string ANSWER_GENERATION_SYSTEM_PROMPT {
            get {
                return ResourceManager.GetString("ANSWER_GENERATION_SYSTEM_PROMPT", resourceCulture);
            }
        }
    }
}
