//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace server.Exceptions {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesErrorMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesErrorMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("server.Exceptions.ResourcesErrorMessages", typeof(ResourcesErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        public static string ROOM_NAME_EMPTY_OR_TOO_SHORT {
            get {
                return ResourceManager.GetString("ROOM_NAME_EMPTY_OR_TOO_SHORT", resourceCulture);
            }
        }
        
        public static string QUESTION_CANT_BE_EMPTY {
            get {
                return ResourceManager.GetString("QUESTION_CANT_BE_EMPTY", resourceCulture);
            }
        }
        
        public static string ROOM_DOESNT_EXISTS {
            get {
                return ResourceManager.GetString("ROOM_DOESNT_EXISTS", resourceCulture);
            }
        }
        
        public static string AUDIO_NOT_FOUND {
            get {
                return ResourceManager.GetString("AUDIO_NOT_FOUND", resourceCulture);
            }
        }
        
        public static string AUDIO_SIZE_EXCEEDED {
            get {
                return ResourceManager.GetString("AUDIO_SIZE_EXCEEDED", resourceCulture);
            }
        }
        
        public static string AUDIO_INVALID_FORMAT {
            get {
                return ResourceManager.GetString("AUDIO_INVALID_FORMAT", resourceCulture);
            }
        }
        
        public static string AUDIO_INVALID_TYPE {
            get {
                return ResourceManager.GetString("AUDIO_INVALID_TYPE", resourceCulture);
            }
        }
        
        public static string OPENAI_AUDIO_TRANSCRIPTION_FAILED {
            get {
                return ResourceManager.GetString("OPENAI_AUDIO_TRANSCRIPTION_FAILED", resourceCulture);
            }
        }
        
        public static string OPENAI_EMBEDDINGS_GENERATION_FAILED {
            get {
                return ResourceManager.GetString("OPENAI_EMBEDDINGS_GENERATION_FAILED", resourceCulture);
            }
        }
        
        public static string OPENAI_RESPONSE_FAILED {
            get {
                return ResourceManager.GetString("OPENAI_RESPONSE_FAILED", resourceCulture);
            }
        }
        
        public static string OPENAI_TRANSCRIBE_AUDIO_ERROR {
            get {
                return ResourceManager.GetString("OPENAI_TRANSCRIBE_AUDIO_ERROR", resourceCulture);
            }
        }
        
        public static string OPENAI_GENERATE_EMBEDDINGS_ERROR {
            get {
                return ResourceManager.GetString("OPENAI_GENERATE_EMBEDDINGS_ERROR", resourceCulture);
            }
        }
        
        public static string OPENAI_GENERATE_ANSWER_ERROR {
            get {
                return ResourceManager.GetString("OPENAI_GENERATE_ANSWER_ERROR", resourceCulture);
            }
        }
    }
}
